# Generated by Django 5.2.12 on 2026-05-28 01:51

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=29.95, help_text='Hourly volunteer rate for this state/county', max_digits=6)),
                ('skilled_hourly_rate', models.DecimalField(decimal_places=2, default=45.0, help_text='Hourly rate for skilled volunteers for this state/county', max_digits=6)),
                ('declaration_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('process_step', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
                ('goal', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_of_donation', models.DateField()),
                ('total_hours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(18)])),
                ('location_donated', models.CharField(max_length=100)),
                ('work_desc', models.TextField(max_length=500)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('other_donation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('donation_type', models.CharField(choices=[('material', 'Material'), ('equipment', 'Equipment'), ('money', 'Money'), ('other', 'Other')], max_length=50)),
                ('material_type', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('money_donated', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(999999.99)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.JSONField(blank=True, null=True)),
                ('disaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_of_work', models.DateField()),
                ('total_hours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(18)])),
                ('location_volunteered', models.CharField(max_length=100)),
                ('work_desc', models.TextField(max_length=500)),
                ('equipment', models.CharField(blank=True, choices=[('chainsaw', 'Chainsaw'), ('pole_saw', 'Pole Saw'), ('shovel', 'Shovel'), ('rake', 'Rake'), ('wheelbarrow', 'Wheelbarrow'), ('generator', 'Generator'), ('extension_cords', 'Extension Cords'), ('shop_vac', 'Shop Vac / Wet-Dry Vacuum'), ('pressure_washer', 'Pressure Washer'), ('truck', 'Truck'), ('trailer', 'Trailer'), ('atv', 'ATV / UTV'), ('ladder', 'Ladder'), ('drill_tools', 'Power Tools'), ('hand_tools', 'Hand Tools'), ('tarps', 'Tarps'), ('safety_gear', 'Safety Gear'), ('none', 'None'), ('other', 'Other')], max_length=50, null=True)),
                ('other_equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_make_model', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skilled_worker', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10, null=True)),
                ('confirmed_skilled_worker', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
