# Generated by Django 4.2.25 on 2026-03-25 23:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('declaration_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('process_step', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_of_work', models.DateField()),
                ('total_hours', models.IntegerField()),
                ('location_volunteered', models.CharField(max_length=100)),
                ('work_desc', models.TextField(max_length=500)),
                ('equipment_used', models.BooleanField(default=False)),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_make_model', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(max_length=500)),
                ('flagged', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date_of_donation', models.DateField()),
                ('total_hours', models.IntegerField(max_length=100)),
                ('location_donated', models.CharField(max_length=100)),
                ('work_desc', models.TextField(max_length=500)),
                ('notes', models.TextField(max_length=500)),
                ('donation_type', models.CharField(choices=[('material', 'Material'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=50)),
                ('material_type', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
