# Generated by Django 5.2.7 on 2026-03-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='equipment_used',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='equipment',
            field=models.CharField(blank=True, choices=[('chainsaw', 'Chainsaw'), ('pole_saw', 'Pole Saw'), ('shovel', 'Shovel'), ('rake', 'Rake'), ('wheelbarrow', 'Wheelbarrow'), ('generator', 'Generator'), ('extension_cords', 'Extension Cords'), ('shop_vac', 'Shop Vac / Wet-Dry Vacuum'), ('pressure_washer', 'Pressure Washer'), ('truck', 'Truck'), ('trailer', 'Trailer'), ('atv', 'ATV / UTV'), ('ladder', 'Ladder'), ('drill_tools', 'Power Tools'), ('hand_tools', 'Hand Tools'), ('tarps', 'Tarps'), ('safety_gear', 'Safety Gear'), ('first_aid', 'First Aid Kit'), ('none', 'None'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='other_equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
