# Generated by Django 5.2.7 on 2026-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_volunteer_equipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='total_hours',
            field=models.IntegerField(),
        ),
    ]
