# Generated by Django 5.2.7 on 2026-03-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_location_alter_donations_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
