# Generated by Django 5.2.7 on 2026-03-29 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_volunteer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
