# Generated by Django 5.2.7 on 2026-03-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_donations_contact_method_volunteer_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')]),
        ),
    ]
