# Generated by Django 5.1.15 on 2026-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_donations_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10),
        ),
    ]
