# Generated by Django 5.2.7 on 2026-03-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_donations_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=29.95, help_text='Hourly volunteer rate for this state/county', max_digits=6),
        ),
    ]
