# Generated by Django 5.2.7 on 2026-03-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_project_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
