# Generated by Django 5.2.7 on 2026-03-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_donations_created_at_volunteer_created_at'),
        ('app', '0009_donations_amount'),
    ]

    operations = [
    ]
