# Generated by Django 5.1.15 on 2026-03-30 16:49

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20260330_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='amount',
        ),
        migrations.AlterField(
            model_name='donations',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='donations',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
