# Generated by Django 5.1.15 on 2026-04-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='skilled_worker',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skilled_worker',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10, null=True),
        ),
    ]
