# Generated by Django 5.1.15 on 2026-04-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_donations_skilled_worker_volunteer_skilled_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='skilled_worker',
        ),
    ]
