# Generated by Django 5.1.15 on 2026-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_donations_skilled_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='flagged_reason',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='other_donation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='flagged_reason',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
