# Generated by Django 5.1.15 on 2026-04-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_donations_flagged_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='confirmed_skilled_worker',
            field=models.BooleanField(default=False),
        ),
    ]
