# Generated by Django 5.2.12 on 2026-04-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_volunteer_confirmed_skilled_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skilled_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=45.0, help_text='Hourly rate for skilled volunteers for this state/county', max_digits=6),
        ),
    ]
