# Generated by Django 5.2.12 on 2026-04-05 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_project_skilled_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='money_donated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donation_type',
            field=models.CharField(choices=[('material', 'Material'), ('equipment', 'Equipment'), ('money', 'Money'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='total_hours',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(18)]),
        ),
    ]
