# Generated by Django 5.2.12 on 2026-04-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_donations_money_donated_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Disaster',
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='project',
            new_name='disaster',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='project',
            new_name='disaster',
        ),
    ]
