# Generated by Django 5.2.12 on 2026-04-11 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_project_disaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='goal',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donations',
            name='money_donated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(999999.99)]),
        ),
        migrations.AlterField(
            model_name='donations',
            name='total_hours',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skilled_worker',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10, null=True),
        ),
    ]
